### ISSUE TITLE
Buy sample tile of commercial imagery

### ISSUE THREAD

**Issue by bw4sz** [weecology/EvergladesWadingBird#3]
@gmyenni let's start making issues here to keep track?

1. Find a known super colony, get lat long coords
2. Find 30cm imagery https://services.hxgncontent.com/admin/shop.do
3. Purchase

**Comment by gmyenni** [comment]
Alley North: 26.20132, -80.52873

**Comment by bw4sz** [comment]
what's the best way to pay for this? I'll need to look around at other resources as well. Here is the message from UF geoplan.

He suggested starting with these links:
https://www.fdot.gov/geospatial/aerialmain.shtm

https://fdotwww.blob.core.windows.net/sitefinity/docs/default-source/co-gis/aplus/aerial-status.pdf?sfvrsn=837a7cf9_22
