### ISSUE TITLE
Buy mapbox space

### ISSUE THREAD

**Issue by bw4sz** [weecology/EvergladesWadingBird#32]
If we are going to upload a ton of data, we should see if we can prepay

https://account.mapbox.com/settings/billing

<img width="1247" alt="Screen Shot 2020-05-21 at 12 30 56 PM" src="https://user-images.githubusercontent.com/1208492/82598172-141f1080-9b5f-11ea-889a-8cac55419db2.png">

I see something about prepaid, but I'll need to dig in.

@gmyenni what's process for paying?

**Comment by gmyenni** [comment]
What's the amount?

**Comment by bw4sz** [comment]
no idea! To do.

**Comment by bw4sz** [comment]
I think 1000$ would be a good start, especially if we have a short-term window to spend.
