### ISSUE TITLE
Update spatial regions files to include subregions and ENP

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesWadingBird#66]
This appears to be the standard breakdown and @skmorgane confirms that due to differences in water management this is what we want:

![Screenshot from 2022-06-12 10-43-32](https://user-images.githubusercontent.com/744427/173238712-826ace2b-9eeb-4419-bc31-1a26d876b80d.png)

So I think we want each of the sub regions, all of them combined, and all of the WCAs combined (i.e., without ENP).

**Comment by gmyenni** [comment]
#64
