### ISSUE TITLE
Create a single species selector than click the bounding boxes

### ISSUE THREAD

**Issue by bw4sz** [weecology/EvergladesWadingBird#8]
See the penguin watch example.

This will reduce clicking.

**Comment by gmyenni** [comment]
I think I've figured out how to do this. I've added it as a new workflow (Label by Species).

But I'm getting an error, so I can't test it. Have you seen the Cannot read property 'type' of undefined . . . error?

**Comment by gmyenni** [comment]
Thanks @bw4sz for fixing error.
